### ISSUE TITLE
LearningSuite grading

### ISSUE THREAD

**Issue by Cardoza2** [byuflowlab/undergrad-onboarding#13]
I was just looking at the LearningSuite grade distribution, and I realized it doesn't look like the time spent is worth 50% of their grade. We might need to revisit that grade distribution.

**Comment by juddmehr** [comment]
I'm fairly certain I had things set up as weighted categories before, but now they aren't weighted, and I don't have any options available to change that.  I think Dr. Ning would have to change that, or we'd have to update things manually.
As it is though, everyone is getting an A or A- already, so I'm not sure it matters.

**Comment by juddmehr** [comment]
Probably no need to update this.  Can rearrange points in future semesters.
