### ISSUE TITLE
Airframe Design assignment

### ISSUE THREAD

**Issue by Cardoza2** [byuflowlab/undergrad-onboarding#14]
I want to have further discussion on how this assignment is laid out. Currently, there doesn't seem to be a good way to have the student provide plots. This might be just me not understanding a good way to have them do this assignment... but I want to have a discussion on it.

**Comment by Cardoza2** [comment]
Like, we could have them design for several different windspeeds, or something, but currently, they could just set their windspeed to really high and then get enough lift. boom.

**Comment by juddmehr** [comment]
This should be able to be resolved with a combination of two fixes:
1. Update the assignment descriptions with better explanations of expectations
2. Have a single grad student in charge of a single project track so that attention isn't divided.

**Comment by juddmehr** [comment]
This may or may not be applicable to the updated assignment structure.  need to have some students try it out.  closing for now.
