### ISSUE TITLE
Assignments Update - Theory Questions

### ISSUE THREAD

**Issue by Cardoza2** [byuflowlab/undergrad-onboarding#8]
I want to add some questions to every assignment that the students have to answer. I've realized the students do better when they have a basic understanding of the theory. I don't mean anything crazy, but we should have an explicit requirement (with points attached) for the students to list the basic assumptions, describe the modeling method, etc. Something a little more explicit than read the chapter and define these words. I still like having them define some words, it's definitely needed, especially on the first assignment. But I think this would bump it a little higher.

**Comment by juddmehr** [comment]
Done in new assignment structure.
